### ISSUE TITLE
Guidelines pour contribuer et autres goodies

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#30]
Je remarque en fait que Mangaki manque de plusieurs fichiers qui constituent un ""standard"" afin de guider les contributeurs:

* [x] CONTRIBUTING.md (quelques guidelines & informations pour aider les nouveaux contributeurs)
* [x] AUTHORS (pas besoin d'expliquer)
* [x] .gitattributes (pour streamliner les contributions)
* ~~Peut-être un CHANGELOG.md ?~~ Il est préférable d'écrire les notes de version avec GitHub Releases nous-même à la main.
* [x] **Éventuellement** un .mailmap ?

Hormis ça, améliorer le .editorconfig serait pas mal.
(meta issue :heart:)

**Comment by jilljenn** [comment]
Bonne idée. Je ne sais pas comment marche un système à base de tags/versions mais je vous laisse faire. Tout ceci doit être au point avant qu'on fasse un premier rush en janvier.

**Comment by RaitoBezarius** [comment]
Closed via #42, <3.
