### ISSUE TITLE
[Umbrella] WorkCluster improvements & ideas

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#548]
## `WorkCluster` and Celery background tasks applications

- [x] Difficulty level of a WorkCluster based on its changeset (roughly: number of choices required and their innate complexity, e.g. start date vs external poster).
- [ ] Detect dead links for external posters.
- [x] More criteria for suggestions in the field changeset (e.g. when you have N equal values and K null values and your total is N + K, choose the first from N equal values and set it as suggestions).
- [x] Under a certain difficulty level, auto-merge a work cluster (!). (free deduplication).

**Comment by jilljenn** [comment]
🚀
